language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
branches:
  only:
    - master
script:
  - dotnet build -c Release --no-cache .\src\HappyCode.NetCoreBoilerplate.Api\
after_success:
  - dotnet test .\test\HappyCode.NetCoreBoilerplate.Api.IntegrationTests\
  - dotnet test .\test\HappyCode.NetCoreBoilerplate.Api.UnitTests\
  - dotnet test .\test\HappyCode.NetCoreBoilerplate.Core.UnitTests\
notifications:
  email:
    on_success: never
    on_failure: always
