pool:
 name: winbayeragentpool
 demands:
 - msbuild
 - visualstudio
 - vstest
 - java

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: 'HappyCode.NetCoreBoilerplate.sln'
    feedsToUse: 'config'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'HappyCode.NetCoreBoilerplate.sln'
    arguments: '--output $(Build.SourcesDirectory)/target/'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test/HappyCode.NetCoreBoilerplate.Api.IntegrationTests/HappyCode.NetCoreBoilerplate.Api.IntegrationTests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '$(Build.ArtifactStagingDirectory)'
    Contents: 'HappyCode.NetCoreBoilerplate.Api.zip'
    ArtifactName: 'Aadeshartifacts'
    ArtifactType: 'Container'