pool:
 name: winbayeragentpool
 demands:
 - msbuild
 - visualstudio
 - vstest
 - java

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

