pool:
 name: winbayeragentpool
 demands:
 - msbuild
 - visualstudio
 - vstest
 - java

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'HappyCode.NetCoreBoilerplate.sln'
    arguments: '--output $(Build.ArtifactStagingDirectory)/target/'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/HappyCode.NetCoreBoilerplate.Api.IntegrationTests/HappyCode.NetCoreBoilerplate.Api.IntegrationTests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'