pool:
 name: winbayeragentpool
 demands:
 - msbuild
 - visualstudio
 - vstest
 - java

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'HappyCode.NetCoreBoilerplate.sln'
    arguments: '-o $(build.artifactstagingdirectory)/target/'
