pool:
 name: winbayeragentpool
 demands:
 - msbuild
 - visualstudio
 - vstest
 - java
variables:
 solution: 'HappyCode.NetCoreBoilerplate.sln'
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'

steps:

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'bayerplate'
    projectName: 'bayerplate'
    extraProperties: 'sonar.flex.cobertura.reportPaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml'
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'config'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--output $(Build.SourcesDirectory)/target/'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test/HappyCode.NetCoreBoilerplate.Api.IntegrationTests/HappyCode.NetCoreBoilerplate.Api.IntegrationTests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'
- task: SonarQubePublish@4
  displayName: 'Publish Quality Gate Result'
- task: sonar-buildbreaker@8
  inputs:
    SonarQube: 'SonarQube'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '$(Build.ArtifactStagingDirectory)'
    Contents: 'HappyCode.NetCoreBoilerplate.Api.zip'
    ArtifactName: 'Aadeshartifacts'
    ArtifactType: 'Container'


